name: Auto Backup

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: سحب المشروع
        uses: actions/checkout@v3

      - name: نسخ الملفات
        run: |
          git clone https://github.com/5efij/backup-repo.git
          rsync -av --exclude='.git' ./ backup-repo/
          
          cd backup-repo
          git config user.name "backup-bot"
          git config user.email "bot@test.com"
          git add .
          git commit -m "backup update" || echo "no changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/5efij/backup-repo.git
