name: Auto Backup

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: نسخ المشروع للباك اب
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          src_path: .
          dst_path: .
          dst_owner: 5efij
          dst_repo_name: backup-repo
