name: Auto Backup

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # مهم جداً 🔥

    steps:
      - name: سحب المشروع
        uses: actions/checkout@v3

      - name: نسخ للباك اب
        run: |
          git config --global user.name "backup-bot"
          git config --global user.email "bot@test.com"

          git clone https://github.com/5efij/backup-repo.git
          
          rsync -av --exclude='.git' ./ backup-repo/

          cd backup-repo
          git add .
          git commit -m "backup update" || echo "no changes"
          git push
